title: Trigger-FK.github.io
description: All is just tasting
  
baseurl: ""
url: "https://trigger-fk.github.io"

author:
  name: Zakimatsu
  # email: mail@examples.com
  github: Trigger-FK
  twitter: santana_hammer

paginate: 5
paginate_path: "page:num"

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed