title: Trigger-FK.github.io
description: >
  
baseurl: ""
url: ""

author:
  name: Zakimatsu
  email: d2mba022@eng.kitakyu-u.ac.jp
  github: Trigger-FK
  twitter: santana_hammer

paginate: 3
paginate_path: "page:num"

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed