title: Trigger-FK.github.io
description: >
  
baseurl: ""
url: ""

author:
  name: Zakimatsu
  # email: mail@examples.com
  github: Trigger-FK
  twitter: santana_hammer

paginate: 5
paginate_path: "page:num"

sass:
  style: expanded

gems:
  - jekyll-paginate
  - jekyll-feed