baseURL = "http://trigger-fk.github.io/"
title = "Fumiya Matsuzaki"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Fumiya Matsuzaki"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Fumiya Matsuzaki's personal website"
# keywords = "blog,developer,personal"
# info = ["Full Stack DevOps", "Magician"]
avatarURL = "images/avatar.jpg"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"

since = 2023

enableTwemoji = true

colorScheme = "white"
hidecolorschemetoggle = true

[languages]
    [languages.en]
        contentDir = 'content/'
        languagename = "English"
        title = "Fumiya Matsuzaki"

        [languages.en.params]
        author = "Fumiya Matsuzaki"
        info = "PhD Student in Control Engineering/Theory"
        description = "Fumiya Matsuzaki's personal website"
        keywords = ""
        avatarURL = "images/avatar.jpg"

    [[languages.en.params.social]]
        name = "Github"
        icon = "fa-brands fa-github fa-2x"
        weight = 1
        url = "https://github.com/trigger-fk/"
    [[languages.en.params.social]]
        name = "Linkedin"
        icon = "fa-brands fa-linkedin fa-2x"
        weight = 2
        url = "https://www.linkedin.com/in/fumiya-matsuzaki-109797316/"
    [[languages.en.params.social]]
        name = "Google Scholar"
        icon = "fa-brands fa-google-scholar fa-2x"
        weight = 3
        url = "https://scholar.google.com/citations?user=E7f8GNgAAAAJ&hl=en"
    [[languages.en.params.social]]
        name = "Research map"
        icon = "fa-regular fa-circle-user fa-2x"
        weight = 4
        url = "https://researchmap.jp/f-matsuzaki?lang=en"

    # Menu links
    [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"
    [[languages.en.menu.main]]
        name = "Publications"
        weight = 2
        url = "publications/"
    [[languages.en.menu.main]]
        name = "Activities"
        weight = 3
        url = "activities/"

[caches]
    [caches.images]
        dir = ':cacheDir/images'