baseurl = "https://trigger-fk.github.io/"
title = "Fumiya Matsuzaki"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "fumiya-matsuzaki"

[markup.highlight]
style = "github"

[params]
  langseparator = "|"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "white"
  hidecolorschemetoggle = true

  customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[languages]
  [languages.en]
    contentDir = 'content/en'
    languagename = "English"
    title = "Fumiya Matsuzaki"

    [languages.en.params]
    author = "Fumiya Matsuzaki"
    info = "PhD Student in Control Engineering/Theory"
    description = "Fumiya Matsuzaki's personal website"
    keywords = ""
    avatarURL = "images/avatar.jpg"

  [[languages.en.params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/trigger-fk/"
  [[languages.en.params.social]]
    name = "Linkedin"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/fumiya-matsuzaki-109797316/"
  [[languages.en.params.social]]
    name = "Google Scholar"
    icon = "fa-brands fa-google-scholar fa-2x"
    weight = 3
    url = "https://scholar.google.com/citations?user=E7f8GNgAAAAJ&hl=en"
  [[languages.en.params.social]]
    name = "Research map"
    icon = "fa-regular fa-circle-user fa-2x"
    weight = 4
    url = "https://researchmap.jp/f-matsuzaki?lang=en"

    # Menu links
    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"
    [[languages.en.menu.main]]
      name = "Publications"
      weight = 2
      url = "publications/"
    [[languages.en.menu.main]]
      name = "Activities"
      weight = 3
      url = "activities/"

  # [languages.ja]
  #   contentDir = 'content/ja'
  #   languagename = "Japanese"
  #   title = "松崎 史弥"

  # [languages.ja.params]
  #   author = "松崎 史弥"
  #   description = "松崎 史弥の個人サイト"
  #   keywords = ""
  #   info = "九州大学大学院 博士後期課程"
  #   avatarurl = "images/avatar.jpg"

  # [[languages.ja.params.social]]
  #   name = "Github"
  #   icon = "fa-brands fa-github fa-2x"
  #   weight = 1
  #   url = "https://github.com/trigger-fk/"
  # [[languages.ja.params.social]]
  #   name = "Linkedin"
  #   icon = "fa-brands fa-linkedin fa-2x"
  #   weight = 2
  #   url = "https://www.linkedin.com/in/fumiya-matsuzaki-109797316/"
  # [[languages.ja.params.social]]
  #   name = "Google Scholar"
  #   icon = "fa-brands fa-google-scholar fa-2x"
  #   weight = 3
  #   url = "https://scholar.google.com/citations?user=E7f8GNgAAAAJ&hl=en"
  # [[languages.ja.params.social]]
  #   name = "Research map"
  #   icon = "fa-regular fa-circle-user fa-2x"
  #   weight = 4
  #   url = "https://researchmap.jp/f-matsuzaki?lang=ja"

  # [languages.ja.menu]
  #   [[languages.ja.menu.main]]
  #     name = "経歴"
  #     weight = 1.0
  #     url = "about/"

  #   [[languages.ja.menu.main]]
  #     name = "業績"
  #     weight = 2.0
  #     url = "publications/"

  #   [[languages.ja.menu.main]]
  #     name = "学外活動"
  #     weight = 3.0
  #     url = "activities/"

  [caches]
  [caches.images]
    dir = ':cacheDir/images'